### ISSUE TITLE
Bitcoin Cash(Mainnet) fails on restore (sync after prolonged period of inactivity)

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/bank-wallet-android#771] opened 2019-03-26 10:41 UTC

**Comment by esengulov** [comment] 2019-03-27 09:06
The restore wallet feature doesn't work on Android while it works on iOS as expected. It applies to initial restore as well as the sync after prolonged idle time (ex: 3 weeks of not accessing the wallet)

Considering that initial wallet restore functionality in BANK is not decentralized yet it's likely that it's a bug on the logic on.Android client. Therefore the bug should be fixed on Android and at the same time it's essential to refactor logic to ensure that it matches the logic on iOS client. We don't want them to be different.

**Comment by rafaelekol** [comment] 2019-03-29 05:50
In case BCH wasn't restored successfully, on opening app after 3 weeks could try to restore BCH again.  Then it would fail by the Bug caused by parser during restore. This bug was fixed by this [pull request](https://github.com/horizontalsystems/bitcoin-kit-android/pull/259).

**Comment by esengulov** [comment] 2019-03-29 06:18
> In case BCH wasn't restored successfully, on opening app after 3 weeks it could try to restore BCH again. Then it would fail by the Bug caused by parser during restore. This bug was fixed by this [pull request](https://github.com/horizontalsystems/bitcoin-kit-android/pull/259).

Got it. It's highly likely that sync bug I was mentioning was actually a restore bug. Consider the issue closed for the time being.

**Closed by esengulov** 2019-03-29 06:18 UTC
Labels: bug, priority
